// Pure (no Playwright) locator-candidate logic for the Phase C hardening pass.
// Given a descriptor of an element (read from the live DOM by harden.server.ts),
// produce candidate locators in most→least stable order. The hardening engine then
// VALIDATES each candidate against the real page (unique + same element) and keeps the
// best survivor + fallbacks — so wrong guesses here are simply filtered out downstream.
// See docs/codegen-reliable-selectors.md.
import type { Locator } from "@/lib/locator";

export type ElementDescriptor = {
  tag: string;
  id?: string;
  testid?: string;
  name?: string;
  type?: string;
  role?: string; // explicit role attribute, if any
  ariaLabel?: string;
  placeholder?: string;
  text?: string; // trimmed visible text
  labelText?: string; // associated <label> text
};

// Maps a tag/type to its implicit ARIA role for the common interactive elements.
export function implicitRole(tag: string, type?: string): string | undefined {
  const t = tag.toLowerCase();
  if (t === "button") return "button";
  if (t === "a") return "link";
  if (t === "select") return "combobox";
  if (t === "textarea") return "textbox";
  if (t === "h1" || t === "h2" || t === "h3" || t === "h4" || t === "h5" || t === "h6")
    return "heading";
  if (t === "img") return "img";
  if (t === "input") {
    switch ((type || "text").toLowerCase()) {
      case "submit":
      case "button":
      case "reset":
        return "button";
      case "checkbox":
        return "checkbox";
      case "radio":
        return "radio";
      case "search":
        return "searchbox";
      case "email":
      case "tel":
      case "url":
      case "text":
      case "password": // note: password has no distinct role; treated as textbox-ish
        return "textbox";
      default:
        return "textbox";
    }
  }
  return undefined;
}

// Heuristic: does this id look framework-generated (hashes, long digit runs, colons)?
// Such ids are unstable, so we avoid using them as a CSS fallback.
export function looksAutoGenerated(id: string): boolean {
  if (id.includes(":")) return true; // e.g. radix "r1:" ids
  if (/\d{3,}/.test(id)) return true; // long digit run (mui-12345)
  if (/[a-f0-9]{6,}/i.test(id)) return true; // hash-like run
  // a delimiter-suffixed token (>=3 chars) mixing letters and digits, e.g. "-2f9a", "-x82a9f"
  const parts = id.split(/[-_]/);
  const last = parts[parts.length - 1];
  return parts.length > 1 && last.length >= 3 && /[a-z]/i.test(last) && /\d/.test(last);
}

// Builds candidate locators for a descriptor, ordered most→least stable. Pure: does not
// check the page — that's the validation step's job.
export function candidatesFromDescriptor(desc: ElementDescriptor): Locator[] {
  const out: Locator[] = [];
  const text = desc.text && desc.text.length <= 60 ? desc.text : undefined;

  // 1. testid
  if (desc.testid) out.push({ by: "testid", value: desc.testid });

  // 2. role + accessible name
  const role = desc.role || implicitRole(desc.tag, desc.type);
  const accName =
    desc.ariaLabel ||
    (role === "button" || role === "link" || role === "heading" ? text : undefined);
  if (role && accName) out.push({ by: "role", role, name: accName });

  // 3. label (form controls)
  if (desc.labelText) out.push({ by: "label", value: desc.labelText });

  // 4. placeholder
  if (desc.placeholder) out.push({ by: "placeholder", value: desc.placeholder });

  // 5. text (short, for clickable/visible elements)
  if (text && (role === "button" || role === "link" || desc.tag === "a" || desc.tag === "button"))
    out.push({ by: "text", value: text });

  // 6. CSS fallbacks — a stable id, then a name-scoped selector, then bare tag.
  if (desc.id && !looksAutoGenerated(desc.id)) out.push({ by: "css", value: `#${desc.id}` });
  if (desc.name) out.push({ by: "css", value: `${desc.tag}[name="${desc.name}"]` });

  return dedupe(out);
}

// --- Phase E: developer-facing data-testid advice ---------------------------------

const ROLE_SUFFIX: Record<string, string> = {
  button: "button",
  link: "link",
  textbox: "input",
  searchbox: "search",
  checkbox: "checkbox",
  radio: "radio",
  combobox: "select",
};

// Kebab-cases a human string into a testid-friendly token.
export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

// Suggests a data-testid name for an element from its most meaningful label + role.
export function suggestTestId(desc: ElementDescriptor): string {
  const base = slugify(
    desc.ariaLabel ||
      desc.labelText ||
      desc.text ||
      desc.placeholder ||
      desc.name ||
      desc.id ||
      desc.tag ||
      "element",
  );
  const role = desc.role || implicitRole(desc.tag, desc.type);
  const suffix = role ? ROLE_SUFFIX[role] : undefined;
  if (!base) return suffix || desc.tag || "element";
  if (suffix && !base.endsWith(suffix)) return `${base}-${suffix}`.slice(0, 50);
  return base;
}

function dedupe(locs: Locator[]): Locator[] {
  const seen = new Set<string>();
  const out: Locator[] = [];
  for (const l of locs) {
    const key = JSON.stringify(l);
    if (!seen.has(key)) {
      seen.add(key);
      out.push(l);
    }
  }
  return out;
}
