import { describe, it, expect } from "vitest";
import {
  implicitRole,
  looksAutoGenerated,
  candidatesFromDescriptor,
  slugify,
  suggestTestId,
} from "./harden-core";

describe("implicitRole", () => {
  it("maps common tags/types", () => {
    expect(implicitRole("button")).toBe("button");
    expect(implicitRole("a")).toBe("link");
    expect(implicitRole("input", "submit")).toBe("button");
    expect(implicitRole("input", "checkbox")).toBe("checkbox");
    expect(implicitRole("input", "email")).toBe("textbox");
    expect(implicitRole("h2")).toBe("heading");
    expect(implicitRole("div")).toBeUndefined();
  });
});

describe("looksAutoGenerated", () => {
  it("flags hashes / digit runs / random suffixes", () => {
    expect(looksAutoGenerated("email-x82a9f")).toBe(true);
    expect(looksAutoGenerated("toast-2f9a")).toBe(true);
    expect(looksAutoGenerated("radix-:r1:")).toBe(true);
    expect(looksAutoGenerated("mui-12345")).toBe(true);
  });
  it("accepts stable, human ids", () => {
    expect(looksAutoGenerated("username")).toBe(false);
    expect(looksAutoGenerated("login-form")).toBe(false);
    expect(looksAutoGenerated("flash")).toBe(false);
  });
});

describe("candidatesFromDescriptor", () => {
  it("ranks testid first, then role+name, then css", () => {
    const cands = candidatesFromDescriptor({
      tag: "button",
      testid: "submit-btn",
      text: "Sign in",
      id: "login",
    });
    expect(cands[0]).toEqual({ by: "testid", value: "submit-btn" });
    expect(cands[1]).toEqual({ by: "role", role: "button", name: "Sign in" });
    expect(cands).toContainEqual({ by: "css", value: "#login" });
  });

  it("derives role+name from text for buttons and links", () => {
    const cands = candidatesFromDescriptor({ tag: "a", text: "Home" });
    expect(cands[0]).toEqual({ by: "role", role: "link", name: "Home" });
    expect(cands).toContainEqual({ by: "text", value: "Home" });
  });

  it("uses label and placeholder for inputs, and skips auto-generated ids", () => {
    const cands = candidatesFromDescriptor({
      tag: "input",
      type: "password",
      id: "pw-9f3a2b",
      labelText: "Password",
      placeholder: "Enter password",
      name: "password",
    });
    expect(cands).toContainEqual({ by: "label", value: "Password" });
    expect(cands).toContainEqual({ by: "placeholder", value: "Enter password" });
    // auto-generated id must NOT appear as a css candidate
    expect(cands.find((c) => c.by === "css" && c.value === "#pw-9f3a2b")).toBeUndefined();
    // but a name-scoped css fallback should
    expect(cands).toContainEqual({ by: "css", value: 'input[name="password"]' });
  });

  it("prefers aria-label over text for the accessible name", () => {
    const cands = candidatesFromDescriptor({
      tag: "button",
      ariaLabel: "Close dialog",
      text: "X",
    });
    expect(cands[0]).toEqual({ by: "role", role: "button", name: "Close dialog" });
  });

  it("does not emit role+name without a name, or text for non-clickables", () => {
    const cands = candidatesFromDescriptor({ tag: "div", text: "Some paragraph text" });
    expect(cands.find((c) => c.by === "role")).toBeUndefined();
    expect(cands.find((c) => c.by === "text")).toBeUndefined();
  });
});

describe("slugify", () => {
  it("kebab-cases and trims", () => {
    expect(slugify("Sign In")).toBe("sign-in");
    expect(slugify("  Add to cart!  ")).toBe("add-to-cart");
    expect(slugify("Email address")).toBe("email-address");
  });
});

describe("suggestTestId", () => {
  it("combines a meaningful label with a role suffix", () => {
    expect(suggestTestId({ tag: "button", text: "Login" })).toBe("login-button");
    expect(suggestTestId({ tag: "input", type: "email", labelText: "Email" })).toBe("email-input");
    expect(suggestTestId({ tag: "a", text: "Home" })).toBe("home-link");
  });
  it("prefers aria-label and avoids doubling the suffix", () => {
    expect(suggestTestId({ tag: "button", ariaLabel: "Close", text: "X" })).toBe("close-button");
    expect(suggestTestId({ tag: "button", text: "Submit button" })).toBe("submit-button");
  });
  it("falls back to tag when there is no label", () => {
    expect(suggestTestId({ tag: "section" })).toBe("section");
  });
});
