/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedCodegenRouteImport } from './routes/_authenticated/codegen'
import { Route as AuthenticatedApiTesterRouteImport } from './routes/_authenticated/api-tester'
import { Route as ApiPublicRunDueSchedulesRouteImport } from './routes/api/public/run-due-schedules'
import { Route as ApiProtectedUpdateBaselineRouteImport } from './routes/api/protected/update-baseline'
import { Route as ApiProtectedSupportChatRouteImport } from './routes/api/protected/support-chat'
import { Route as ApiProtectedSeedDemoRouteImport } from './routes/api/protected/seed-demo'
import { Route as ApiProtectedScreenshotUrlRouteImport } from './routes/api/protected/screenshot-url'
import { Route as ApiProtectedSaveVariablesRouteImport } from './routes/api/protected/save-variables'
import { Route as ApiProtectedRunTestsRouteImport } from './routes/api/protected/run-tests'
import { Route as ApiProtectedRunTestRouteImport } from './routes/api/protected/run-test'
import { Route as ApiProtectedRunDatasetRouteImport } from './routes/api/protected/run-dataset'
import { Route as ApiProtectedRefreshDatasetRouteImport } from './routes/api/protected/refresh-dataset'
import { Route as ApiProtectedRecordCodegenRouteImport } from './routes/api/protected/record-codegen'
import { Route as ApiProtectedHardenTestRouteImport } from './routes/api/protected/harden-test'
import { Route as ApiProtectedHardenProjectRouteImport } from './routes/api/protected/harden-project'
import { Route as ApiProtectedDeleteTestRouteImport } from './routes/api/protected/delete-test'
import { Route as ApiProtectedDeleteProjectRouteImport } from './routes/api/protected/delete-project'
import { Route as ApiProtectedConnectDatasetSourceRouteImport } from './routes/api/protected/connect-dataset-source'
import { Route as ApiProtectedAiHealSelectorRouteImport } from './routes/api/protected/ai-heal-selector'
import { Route as ApiProtectedAiGenerateTestRouteImport } from './routes/api/protected/ai-generate-test'
import { Route as ApiProtectedAiGenerateApiSuiteRouteImport } from './routes/api/protected/ai-generate-api-suite'
import { Route as ApiProtectedAiCodegenRouteImport } from './routes/api/protected/ai-codegen'
import { Route as ApiProtectedAiAnalyzeFailureRouteImport } from './routes/api/protected/ai-analyze-failure'
import { Route as ApiProtectedAdviseLocatorsRouteImport } from './routes/api/protected/advise-locators'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests.$testId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodegenRoute = AuthenticatedCodegenRouteImport.update({
  id: '/codegen',
  path: '/codegen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiTesterRoute = AuthenticatedApiTesterRouteImport.update({
  id: '/api-tester',
  path: '/api-tester',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicRunDueSchedulesRoute =
  ApiPublicRunDueSchedulesRouteImport.update({
    id: '/api/public/run-due-schedules',
    path: '/api/public/run-due-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedUpdateBaselineRoute =
  ApiProtectedUpdateBaselineRouteImport.update({
    id: '/api/protected/update-baseline',
    path: '/api/protected/update-baseline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedSupportChatRoute = ApiProtectedSupportChatRouteImport.update({
  id: '/api/protected/support-chat',
  path: '/api/protected/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedSeedDemoRoute = ApiProtectedSeedDemoRouteImport.update({
  id: '/api/protected/seed-demo',
  path: '/api/protected/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedScreenshotUrlRoute =
  ApiProtectedScreenshotUrlRouteImport.update({
    id: '/api/protected/screenshot-url',
    path: '/api/protected/screenshot-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedSaveVariablesRoute =
  ApiProtectedSaveVariablesRouteImport.update({
    id: '/api/protected/save-variables',
    path: '/api/protected/save-variables',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedRunTestsRoute = ApiProtectedRunTestsRouteImport.update({
  id: '/api/protected/run-tests',
  path: '/api/protected/run-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedRunTestRoute = ApiProtectedRunTestRouteImport.update({
  id: '/api/protected/run-test',
  path: '/api/protected/run-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedRunDatasetRoute = ApiProtectedRunDatasetRouteImport.update({
  id: '/api/protected/run-dataset',
  path: '/api/protected/run-dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedRefreshDatasetRoute =
  ApiProtectedRefreshDatasetRouteImport.update({
    id: '/api/protected/refresh-dataset',
    path: '/api/protected/refresh-dataset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedRecordCodegenRoute =
  ApiProtectedRecordCodegenRouteImport.update({
    id: '/api/protected/record-codegen',
    path: '/api/protected/record-codegen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedHardenTestRoute = ApiProtectedHardenTestRouteImport.update({
  id: '/api/protected/harden-test',
  path: '/api/protected/harden-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedHardenProjectRoute =
  ApiProtectedHardenProjectRouteImport.update({
    id: '/api/protected/harden-project',
    path: '/api/protected/harden-project',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedDeleteTestRoute = ApiProtectedDeleteTestRouteImport.update({
  id: '/api/protected/delete-test',
  path: '/api/protected/delete-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedDeleteProjectRoute =
  ApiProtectedDeleteProjectRouteImport.update({
    id: '/api/protected/delete-project',
    path: '/api/protected/delete-project',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedConnectDatasetSourceRoute =
  ApiProtectedConnectDatasetSourceRouteImport.update({
    id: '/api/protected/connect-dataset-source',
    path: '/api/protected/connect-dataset-source',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiHealSelectorRoute =
  ApiProtectedAiHealSelectorRouteImport.update({
    id: '/api/protected/ai-heal-selector',
    path: '/api/protected/ai-heal-selector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiGenerateTestRoute =
  ApiProtectedAiGenerateTestRouteImport.update({
    id: '/api/protected/ai-generate-test',
    path: '/api/protected/ai-generate-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiGenerateApiSuiteRoute =
  ApiProtectedAiGenerateApiSuiteRouteImport.update({
    id: '/api/protected/ai-generate-api-suite',
    path: '/api/protected/ai-generate-api-suite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiCodegenRoute = ApiProtectedAiCodegenRouteImport.update({
  id: '/api/protected/ai-codegen',
  path: '/api/protected/ai-codegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedAiAnalyzeFailureRoute =
  ApiProtectedAiAnalyzeFailureRouteImport.update({
    id: '/api/protected/ai-analyze-failure',
    path: '/api/protected/ai-analyze-failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAdviseLocatorsRoute =
  ApiProtectedAdviseLocatorsRouteImport.update({
    id: '/api/protected/advise-locators',
    path: '/api/protected/advise-locators',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/codegen': typeof AuthenticatedCodegenRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/advise-locators': typeof ApiProtectedAdviseLocatorsRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/connect-dataset-source': typeof ApiProtectedConnectDatasetSourceRoute
  '/api/protected/delete-project': typeof ApiProtectedDeleteProjectRoute
  '/api/protected/delete-test': typeof ApiProtectedDeleteTestRoute
  '/api/protected/harden-project': typeof ApiProtectedHardenProjectRoute
  '/api/protected/harden-test': typeof ApiProtectedHardenTestRoute
  '/api/protected/record-codegen': typeof ApiProtectedRecordCodegenRoute
  '/api/protected/refresh-dataset': typeof ApiProtectedRefreshDatasetRoute
  '/api/protected/run-dataset': typeof ApiProtectedRunDatasetRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
  '/api/protected/run-tests': typeof ApiProtectedRunTestsRoute
  '/api/protected/save-variables': typeof ApiProtectedSaveVariablesRoute
  '/api/protected/screenshot-url': typeof ApiProtectedScreenshotUrlRoute
  '/api/protected/seed-demo': typeof ApiProtectedSeedDemoRoute
  '/api/protected/support-chat': typeof ApiProtectedSupportChatRoute
  '/api/protected/update-baseline': typeof ApiProtectedUpdateBaselineRoute
  '/api/public/run-due-schedules': typeof ApiPublicRunDueSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/codegen': typeof AuthenticatedCodegenRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/advise-locators': typeof ApiProtectedAdviseLocatorsRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/connect-dataset-source': typeof ApiProtectedConnectDatasetSourceRoute
  '/api/protected/delete-project': typeof ApiProtectedDeleteProjectRoute
  '/api/protected/delete-test': typeof ApiProtectedDeleteTestRoute
  '/api/protected/harden-project': typeof ApiProtectedHardenProjectRoute
  '/api/protected/harden-test': typeof ApiProtectedHardenTestRoute
  '/api/protected/record-codegen': typeof ApiProtectedRecordCodegenRoute
  '/api/protected/refresh-dataset': typeof ApiProtectedRefreshDatasetRoute
  '/api/protected/run-dataset': typeof ApiProtectedRunDatasetRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
  '/api/protected/run-tests': typeof ApiProtectedRunTestsRoute
  '/api/protected/save-variables': typeof ApiProtectedSaveVariablesRoute
  '/api/protected/screenshot-url': typeof ApiProtectedScreenshotUrlRoute
  '/api/protected/seed-demo': typeof ApiProtectedSeedDemoRoute
  '/api/protected/support-chat': typeof ApiProtectedSupportChatRoute
  '/api/protected/update-baseline': typeof ApiProtectedUpdateBaselineRoute
  '/api/public/run-due-schedules': typeof ApiPublicRunDueSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/api-tester': typeof AuthenticatedApiTesterRoute
  '/_authenticated/codegen': typeof AuthenticatedCodegenRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/advise-locators': typeof ApiProtectedAdviseLocatorsRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/connect-dataset-source': typeof ApiProtectedConnectDatasetSourceRoute
  '/api/protected/delete-project': typeof ApiProtectedDeleteProjectRoute
  '/api/protected/delete-test': typeof ApiProtectedDeleteTestRoute
  '/api/protected/harden-project': typeof ApiProtectedHardenProjectRoute
  '/api/protected/harden-test': typeof ApiProtectedHardenTestRoute
  '/api/protected/record-codegen': typeof ApiProtectedRecordCodegenRoute
  '/api/protected/refresh-dataset': typeof ApiProtectedRefreshDatasetRoute
  '/api/protected/run-dataset': typeof ApiProtectedRunDatasetRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
  '/api/protected/run-tests': typeof ApiProtectedRunTestsRoute
  '/api/protected/save-variables': typeof ApiProtectedSaveVariablesRoute
  '/api/protected/screenshot-url': typeof ApiProtectedScreenshotUrlRoute
  '/api/protected/seed-demo': typeof ApiProtectedSeedDemoRoute
  '/api/protected/support-chat': typeof ApiProtectedSupportChatRoute
  '/api/protected/update-baseline': typeof ApiProtectedUpdateBaselineRoute
  '/api/public/run-due-schedules': typeof ApiPublicRunDueSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-tester'
    | '/codegen'
    | '/console'
    | '/dashboard'
    | '/datasets'
    | '/docs'
    | '/insights'
    | '/schedules'
    | '/tests/$testId'
    | '/api/protected/advise-locators'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/connect-dataset-source'
    | '/api/protected/delete-project'
    | '/api/protected/delete-test'
    | '/api/protected/harden-project'
    | '/api/protected/harden-test'
    | '/api/protected/record-codegen'
    | '/api/protected/refresh-dataset'
    | '/api/protected/run-dataset'
    | '/api/protected/run-test'
    | '/api/protected/run-tests'
    | '/api/protected/save-variables'
    | '/api/protected/screenshot-url'
    | '/api/protected/seed-demo'
    | '/api/protected/support-chat'
    | '/api/protected/update-baseline'
    | '/api/public/run-due-schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-tester'
    | '/codegen'
    | '/console'
    | '/dashboard'
    | '/datasets'
    | '/docs'
    | '/insights'
    | '/schedules'
    | '/tests/$testId'
    | '/api/protected/advise-locators'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/connect-dataset-source'
    | '/api/protected/delete-project'
    | '/api/protected/delete-test'
    | '/api/protected/harden-project'
    | '/api/protected/harden-test'
    | '/api/protected/record-codegen'
    | '/api/protected/refresh-dataset'
    | '/api/protected/run-dataset'
    | '/api/protected/run-test'
    | '/api/protected/run-tests'
    | '/api/protected/save-variables'
    | '/api/protected/screenshot-url'
    | '/api/protected/seed-demo'
    | '/api/protected/support-chat'
    | '/api/protected/update-baseline'
    | '/api/public/run-due-schedules'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/api-tester'
    | '/_authenticated/codegen'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/docs'
    | '/_authenticated/insights'
    | '/_authenticated/schedules'
    | '/_authenticated/tests/$testId'
    | '/api/protected/advise-locators'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/connect-dataset-source'
    | '/api/protected/delete-project'
    | '/api/protected/delete-test'
    | '/api/protected/harden-project'
    | '/api/protected/harden-test'
    | '/api/protected/record-codegen'
    | '/api/protected/refresh-dataset'
    | '/api/protected/run-dataset'
    | '/api/protected/run-test'
    | '/api/protected/run-tests'
    | '/api/protected/save-variables'
    | '/api/protected/screenshot-url'
    | '/api/protected/seed-demo'
    | '/api/protected/support-chat'
    | '/api/protected/update-baseline'
    | '/api/public/run-due-schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiProtectedAdviseLocatorsRoute: typeof ApiProtectedAdviseLocatorsRoute
  ApiProtectedAiAnalyzeFailureRoute: typeof ApiProtectedAiAnalyzeFailureRoute
  ApiProtectedAiCodegenRoute: typeof ApiProtectedAiCodegenRoute
  ApiProtectedAiGenerateApiSuiteRoute: typeof ApiProtectedAiGenerateApiSuiteRoute
  ApiProtectedAiGenerateTestRoute: typeof ApiProtectedAiGenerateTestRoute
  ApiProtectedAiHealSelectorRoute: typeof ApiProtectedAiHealSelectorRoute
  ApiProtectedConnectDatasetSourceRoute: typeof ApiProtectedConnectDatasetSourceRoute
  ApiProtectedDeleteProjectRoute: typeof ApiProtectedDeleteProjectRoute
  ApiProtectedDeleteTestRoute: typeof ApiProtectedDeleteTestRoute
  ApiProtectedHardenProjectRoute: typeof ApiProtectedHardenProjectRoute
  ApiProtectedHardenTestRoute: typeof ApiProtectedHardenTestRoute
  ApiProtectedRecordCodegenRoute: typeof ApiProtectedRecordCodegenRoute
  ApiProtectedRefreshDatasetRoute: typeof ApiProtectedRefreshDatasetRoute
  ApiProtectedRunDatasetRoute: typeof ApiProtectedRunDatasetRoute
  ApiProtectedRunTestRoute: typeof ApiProtectedRunTestRoute
  ApiProtectedRunTestsRoute: typeof ApiProtectedRunTestsRoute
  ApiProtectedSaveVariablesRoute: typeof ApiProtectedSaveVariablesRoute
  ApiProtectedScreenshotUrlRoute: typeof ApiProtectedScreenshotUrlRoute
  ApiProtectedSeedDemoRoute: typeof ApiProtectedSeedDemoRoute
  ApiProtectedSupportChatRoute: typeof ApiProtectedSupportChatRoute
  ApiProtectedUpdateBaselineRoute: typeof ApiProtectedUpdateBaselineRoute
  ApiPublicRunDueSchedulesRoute: typeof ApiPublicRunDueSchedulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codegen': {
      id: '/_authenticated/codegen'
      path: '/codegen'
      fullPath: '/codegen'
      preLoaderRoute: typeof AuthenticatedCodegenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-tester': {
      id: '/_authenticated/api-tester'
      path: '/api-tester'
      fullPath: '/api-tester'
      preLoaderRoute: typeof AuthenticatedApiTesterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/run-due-schedules': {
      id: '/api/public/run-due-schedules'
      path: '/api/public/run-due-schedules'
      fullPath: '/api/public/run-due-schedules'
      preLoaderRoute: typeof ApiPublicRunDueSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/update-baseline': {
      id: '/api/protected/update-baseline'
      path: '/api/protected/update-baseline'
      fullPath: '/api/protected/update-baseline'
      preLoaderRoute: typeof ApiProtectedUpdateBaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/support-chat': {
      id: '/api/protected/support-chat'
      path: '/api/protected/support-chat'
      fullPath: '/api/protected/support-chat'
      preLoaderRoute: typeof ApiProtectedSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/seed-demo': {
      id: '/api/protected/seed-demo'
      path: '/api/protected/seed-demo'
      fullPath: '/api/protected/seed-demo'
      preLoaderRoute: typeof ApiProtectedSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/screenshot-url': {
      id: '/api/protected/screenshot-url'
      path: '/api/protected/screenshot-url'
      fullPath: '/api/protected/screenshot-url'
      preLoaderRoute: typeof ApiProtectedScreenshotUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/save-variables': {
      id: '/api/protected/save-variables'
      path: '/api/protected/save-variables'
      fullPath: '/api/protected/save-variables'
      preLoaderRoute: typeof ApiProtectedSaveVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/run-tests': {
      id: '/api/protected/run-tests'
      path: '/api/protected/run-tests'
      fullPath: '/api/protected/run-tests'
      preLoaderRoute: typeof ApiProtectedRunTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/run-test': {
      id: '/api/protected/run-test'
      path: '/api/protected/run-test'
      fullPath: '/api/protected/run-test'
      preLoaderRoute: typeof ApiProtectedRunTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/run-dataset': {
      id: '/api/protected/run-dataset'
      path: '/api/protected/run-dataset'
      fullPath: '/api/protected/run-dataset'
      preLoaderRoute: typeof ApiProtectedRunDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/refresh-dataset': {
      id: '/api/protected/refresh-dataset'
      path: '/api/protected/refresh-dataset'
      fullPath: '/api/protected/refresh-dataset'
      preLoaderRoute: typeof ApiProtectedRefreshDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/record-codegen': {
      id: '/api/protected/record-codegen'
      path: '/api/protected/record-codegen'
      fullPath: '/api/protected/record-codegen'
      preLoaderRoute: typeof ApiProtectedRecordCodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/harden-test': {
      id: '/api/protected/harden-test'
      path: '/api/protected/harden-test'
      fullPath: '/api/protected/harden-test'
      preLoaderRoute: typeof ApiProtectedHardenTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/harden-project': {
      id: '/api/protected/harden-project'
      path: '/api/protected/harden-project'
      fullPath: '/api/protected/harden-project'
      preLoaderRoute: typeof ApiProtectedHardenProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/delete-test': {
      id: '/api/protected/delete-test'
      path: '/api/protected/delete-test'
      fullPath: '/api/protected/delete-test'
      preLoaderRoute: typeof ApiProtectedDeleteTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/delete-project': {
      id: '/api/protected/delete-project'
      path: '/api/protected/delete-project'
      fullPath: '/api/protected/delete-project'
      preLoaderRoute: typeof ApiProtectedDeleteProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/connect-dataset-source': {
      id: '/api/protected/connect-dataset-source'
      path: '/api/protected/connect-dataset-source'
      fullPath: '/api/protected/connect-dataset-source'
      preLoaderRoute: typeof ApiProtectedConnectDatasetSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-heal-selector': {
      id: '/api/protected/ai-heal-selector'
      path: '/api/protected/ai-heal-selector'
      fullPath: '/api/protected/ai-heal-selector'
      preLoaderRoute: typeof ApiProtectedAiHealSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-generate-test': {
      id: '/api/protected/ai-generate-test'
      path: '/api/protected/ai-generate-test'
      fullPath: '/api/protected/ai-generate-test'
      preLoaderRoute: typeof ApiProtectedAiGenerateTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-generate-api-suite': {
      id: '/api/protected/ai-generate-api-suite'
      path: '/api/protected/ai-generate-api-suite'
      fullPath: '/api/protected/ai-generate-api-suite'
      preLoaderRoute: typeof ApiProtectedAiGenerateApiSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-codegen': {
      id: '/api/protected/ai-codegen'
      path: '/api/protected/ai-codegen'
      fullPath: '/api/protected/ai-codegen'
      preLoaderRoute: typeof ApiProtectedAiCodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-analyze-failure': {
      id: '/api/protected/ai-analyze-failure'
      path: '/api/protected/ai-analyze-failure'
      fullPath: '/api/protected/ai-analyze-failure'
      preLoaderRoute: typeof ApiProtectedAiAnalyzeFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/advise-locators': {
      id: '/api/protected/advise-locators'
      path: '/api/protected/advise-locators'
      fullPath: '/api/protected/advise-locators'
      preLoaderRoute: typeof ApiProtectedAdviseLocatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApiTesterRoute: typeof AuthenticatedApiTesterRoute
  AuthenticatedCodegenRoute: typeof AuthenticatedCodegenRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiTesterRoute: AuthenticatedApiTesterRoute,
  AuthenticatedCodegenRoute: AuthenticatedCodegenRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiProtectedAdviseLocatorsRoute: ApiProtectedAdviseLocatorsRoute,
  ApiProtectedAiAnalyzeFailureRoute: ApiProtectedAiAnalyzeFailureRoute,
  ApiProtectedAiCodegenRoute: ApiProtectedAiCodegenRoute,
  ApiProtectedAiGenerateApiSuiteRoute: ApiProtectedAiGenerateApiSuiteRoute,
  ApiProtectedAiGenerateTestRoute: ApiProtectedAiGenerateTestRoute,
  ApiProtectedAiHealSelectorRoute: ApiProtectedAiHealSelectorRoute,
  ApiProtectedConnectDatasetSourceRoute: ApiProtectedConnectDatasetSourceRoute,
  ApiProtectedDeleteProjectRoute: ApiProtectedDeleteProjectRoute,
  ApiProtectedDeleteTestRoute: ApiProtectedDeleteTestRoute,
  ApiProtectedHardenProjectRoute: ApiProtectedHardenProjectRoute,
  ApiProtectedHardenTestRoute: ApiProtectedHardenTestRoute,
  ApiProtectedRecordCodegenRoute: ApiProtectedRecordCodegenRoute,
  ApiProtectedRefreshDatasetRoute: ApiProtectedRefreshDatasetRoute,
  ApiProtectedRunDatasetRoute: ApiProtectedRunDatasetRoute,
  ApiProtectedRunTestRoute: ApiProtectedRunTestRoute,
  ApiProtectedRunTestsRoute: ApiProtectedRunTestsRoute,
  ApiProtectedSaveVariablesRoute: ApiProtectedSaveVariablesRoute,
  ApiProtectedScreenshotUrlRoute: ApiProtectedScreenshotUrlRoute,
  ApiProtectedSeedDemoRoute: ApiProtectedSeedDemoRoute,
  ApiProtectedSupportChatRoute: ApiProtectedSupportChatRoute,
  ApiProtectedUpdateBaselineRoute: ApiProtectedUpdateBaselineRoute,
  ApiPublicRunDueSchedulesRoute: ApiPublicRunDueSchedulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
