/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCodegenRouteImport } from './routes/_authenticated/codegen'
import { Route as AuthenticatedApiTesterRouteImport } from './routes/_authenticated/api-tester'
import { Route as ApiProtectedRunTestRouteImport } from './routes/api/protected/run-test'
import { Route as ApiProtectedAiHealSelectorRouteImport } from './routes/api/protected/ai-heal-selector'
import { Route as ApiProtectedAiGenerateTestRouteImport } from './routes/api/protected/ai-generate-test'
import { Route as ApiProtectedAiGenerateApiSuiteRouteImport } from './routes/api/protected/ai-generate-api-suite'
import { Route as ApiProtectedAiCodegenRouteImport } from './routes/api/protected/ai-codegen'
import { Route as ApiProtectedAiAnalyzeFailureRouteImport } from './routes/api/protected/ai-analyze-failure'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests.$testId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodegenRoute = AuthenticatedCodegenRouteImport.update({
  id: '/codegen',
  path: '/codegen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiTesterRoute = AuthenticatedApiTesterRouteImport.update({
  id: '/api-tester',
  path: '/api-tester',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiProtectedRunTestRoute = ApiProtectedRunTestRouteImport.update({
  id: '/api/protected/run-test',
  path: '/api/protected/run-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedAiHealSelectorRoute =
  ApiProtectedAiHealSelectorRouteImport.update({
    id: '/api/protected/ai-heal-selector',
    path: '/api/protected/ai-heal-selector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiGenerateTestRoute =
  ApiProtectedAiGenerateTestRouteImport.update({
    id: '/api/protected/ai-generate-test',
    path: '/api/protected/ai-generate-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiGenerateApiSuiteRoute =
  ApiProtectedAiGenerateApiSuiteRouteImport.update({
    id: '/api/protected/ai-generate-api-suite',
    path: '/api/protected/ai-generate-api-suite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedAiCodegenRoute = ApiProtectedAiCodegenRouteImport.update({
  id: '/api/protected/ai-codegen',
  path: '/api/protected/ai-codegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedAiAnalyzeFailureRoute =
  ApiProtectedAiAnalyzeFailureRouteImport.update({
    id: '/api/protected/ai-analyze-failure',
    path: '/api/protected/ai-analyze-failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/codegen': typeof AuthenticatedCodegenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/codegen': typeof AuthenticatedCodegenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/api-tester': typeof AuthenticatedApiTesterRoute
  '/_authenticated/codegen': typeof AuthenticatedCodegenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRoute
  '/api/protected/ai-analyze-failure': typeof ApiProtectedAiAnalyzeFailureRoute
  '/api/protected/ai-codegen': typeof ApiProtectedAiCodegenRoute
  '/api/protected/ai-generate-api-suite': typeof ApiProtectedAiGenerateApiSuiteRoute
  '/api/protected/ai-generate-test': typeof ApiProtectedAiGenerateTestRoute
  '/api/protected/ai-heal-selector': typeof ApiProtectedAiHealSelectorRoute
  '/api/protected/run-test': typeof ApiProtectedRunTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-tester'
    | '/codegen'
    | '/dashboard'
    | '/schedules'
    | '/tests/$testId'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/run-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-tester'
    | '/codegen'
    | '/dashboard'
    | '/schedules'
    | '/tests/$testId'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/run-test'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/api-tester'
    | '/_authenticated/codegen'
    | '/_authenticated/dashboard'
    | '/_authenticated/schedules'
    | '/_authenticated/tests/$testId'
    | '/api/protected/ai-analyze-failure'
    | '/api/protected/ai-codegen'
    | '/api/protected/ai-generate-api-suite'
    | '/api/protected/ai-generate-test'
    | '/api/protected/ai-heal-selector'
    | '/api/protected/run-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiProtectedAiAnalyzeFailureRoute: typeof ApiProtectedAiAnalyzeFailureRoute
  ApiProtectedAiCodegenRoute: typeof ApiProtectedAiCodegenRoute
  ApiProtectedAiGenerateApiSuiteRoute: typeof ApiProtectedAiGenerateApiSuiteRoute
  ApiProtectedAiGenerateTestRoute: typeof ApiProtectedAiGenerateTestRoute
  ApiProtectedAiHealSelectorRoute: typeof ApiProtectedAiHealSelectorRoute
  ApiProtectedRunTestRoute: typeof ApiProtectedRunTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codegen': {
      id: '/_authenticated/codegen'
      path: '/codegen'
      fullPath: '/codegen'
      preLoaderRoute: typeof AuthenticatedCodegenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-tester': {
      id: '/_authenticated/api-tester'
      path: '/api-tester'
      fullPath: '/api-tester'
      preLoaderRoute: typeof AuthenticatedApiTesterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/protected/run-test': {
      id: '/api/protected/run-test'
      path: '/api/protected/run-test'
      fullPath: '/api/protected/run-test'
      preLoaderRoute: typeof ApiProtectedRunTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-heal-selector': {
      id: '/api/protected/ai-heal-selector'
      path: '/api/protected/ai-heal-selector'
      fullPath: '/api/protected/ai-heal-selector'
      preLoaderRoute: typeof ApiProtectedAiHealSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-generate-test': {
      id: '/api/protected/ai-generate-test'
      path: '/api/protected/ai-generate-test'
      fullPath: '/api/protected/ai-generate-test'
      preLoaderRoute: typeof ApiProtectedAiGenerateTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-generate-api-suite': {
      id: '/api/protected/ai-generate-api-suite'
      path: '/api/protected/ai-generate-api-suite'
      fullPath: '/api/protected/ai-generate-api-suite'
      preLoaderRoute: typeof ApiProtectedAiGenerateApiSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-codegen': {
      id: '/api/protected/ai-codegen'
      path: '/api/protected/ai-codegen'
      fullPath: '/api/protected/ai-codegen'
      preLoaderRoute: typeof ApiProtectedAiCodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/ai-analyze-failure': {
      id: '/api/protected/ai-analyze-failure'
      path: '/api/protected/ai-analyze-failure'
      fullPath: '/api/protected/ai-analyze-failure'
      preLoaderRoute: typeof ApiProtectedAiAnalyzeFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApiTesterRoute: typeof AuthenticatedApiTesterRoute
  AuthenticatedCodegenRoute: typeof AuthenticatedCodegenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiTesterRoute: AuthenticatedApiTesterRoute,
  AuthenticatedCodegenRoute: AuthenticatedCodegenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiProtectedAiAnalyzeFailureRoute: ApiProtectedAiAnalyzeFailureRoute,
  ApiProtectedAiCodegenRoute: ApiProtectedAiCodegenRoute,
  ApiProtectedAiGenerateApiSuiteRoute: ApiProtectedAiGenerateApiSuiteRoute,
  ApiProtectedAiGenerateTestRoute: ApiProtectedAiGenerateTestRoute,
  ApiProtectedAiHealSelectorRoute: ApiProtectedAiHealSelectorRoute,
  ApiProtectedRunTestRoute: ApiProtectedRunTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
